### PR TITLE
Adds legacy .styl files into gulp watch to build dynamically..

### PR DESCRIPTION
**Pull request by davidrkupton**
Adds a gulp task/config to the watch process so that the hub.stly and public.styl in the legacy folder are compiled to css when they are changed.  I did this locally, it may be worth adding to the pattern repo for others ?
@jimafisk @finneganh

### CODE REVIEW

**Review by jimafisk — COMMENTED** [review]
Does `npm run dev` already compile via `gulp-tasks/stylus_legacy.js`?

**Comment by jimafisk** [comment]
legacy

@davidrkupton ^^^

**Comment by davidrkupton** [comment]
@jimafisk for me starting the pattern server `npm run dev` only compiles the css on startup, it doesn't seem to watch the legacy folders.  So I was having to start and stop it each time I wanted to rebuild the `legacy/public.css`. With this mod it rebuilds as I change and save the file.  I am happy to keep this on my version if you don't want it included, but I don't think it does any harm?.

**Comment by jimafisk** [comment]
That seems like a good reason to me for adding your changes. I just wasn't sure if this was already being done. Looks good to merge from my perspective if @finneganh agrees.

**Review by fionawhim — APPROVED** [review]
Don't forget to approve Percy. Sorry for the flakiness there.

**Comment by fionawhim** [comment]
@davidrkupton Can you check this PR in?

**Pull request merged**
