### PR TITLE
- Added styles and media query 

### PR DESCRIPTION
**Pull request by mmcgowanBOS**
Added styles and media query to hide city of Boston logo and show new city B logo in top menu.

* NOTE: this PR should be merged only AFTER the following commit in D7 is merged to Prod.
https://github.com/CityOfBoston/boston.gov-d7/commit/35af42e4c73fa8a960818ab5e033f6715a530b25

### CODE REVIEW

**Comment by jessicamarcus** [comment]
Looking at the Percy results, at mobile viewport widths there’s nothing at all to identify the website in the header. Is this intended behavior?

**Comment by mmcgowanBOS** [comment]
Regarding comment above, Yes, this is the intended behavior. Once the commit / PR mentioned below is deployed to production, there will be a new container DIV and IMG showing a city of Boston "B" logo that will take the previous logo's place now that's it's hidden from display.

Mentioned commit ...
https://github.com/CityOfBoston/boston.gov-d7/pull/1270/commits/0af7fb9e287da7001e6590757214002964a5ae2d

**Comment by jessicamarcus** [comment]
This PR is missing an updated markup example here: https://github.com/CityOfBoston/patterns/tree/develop/components/blocks/header

There are other sites and apps that use the `patterns` CSS library, and they would all have to make markup changes (ex: https://onlinepermitsandlicenses.cityofboston.gov/BFD) to avoid a blank spot in the header. However, if we can come up with a CSS-only solution it would be a seamless update.

The first thought that comes to mind is to use `::before` or `::after` to change out the visual. I’m happy to discuss / brainstorm once I get my own `birth-certs` PR in!

**Comment by mmcgowanBOS** [comment]
I've made another commit and am now using the "content" property to display a different image for the  CoB logo instead of showing / hiding 2 DIVs. With this, I'm still running into some issues with Percy. I'd like to meet and review the Percy issues so this can get approved.

**Pull request closed without merging**
