### PR TITLE
(production) Text Box treatments for data entry states and required fields DIG-4058

### PR DESCRIPTION
**Pull request by phillipbentonkelly**
@subaha-cob I pushed to `develop` and I can see the changes on staging ... created this PR to push to PROD but I see these other stuff, from @davidrkupton, that haven't been merged in. David, are these ok to go to PROD too?

### CODE REVIEW

**Review by davidrkupton — APPROVED** [review]
This is how you deploy patterns

**Comment by davidrkupton** [comment]
Percy is not scanning patterns at the moment,.

**Comment by davidrkupton** [comment]
@phillipbentonkelly - Yes my changes should be OK to merge. What is strange is that `production` is ahead of `develop` not sure how...

**Review by subaha-cob — APPROVED** [review]
LGTM!

**Pull request merged**
