### PR TITLE
Updates .lnk style to override default button

### PR DESCRIPTION
**Pull request by fionawhim**
Lets us use semantic <button> elements in a way that look like links.

### CODE REVIEW

**Comment by fionawhim** [comment]
IE11 clipping descender a bit:

screen shot 2018-10-02 at 9 22 28 am

**Comment by fionawhim** [comment]
Fixed that with `overflow: visible`, though the active state is slightly jank. I think that’s fine though.

screen shot 2018-10-02 at 9 24 28 am

**Comment by fionawhim** [comment]
I think the test failure was flake. Blargh. Running it again.

**Comment by fionawhim** [comment]
ooorrrr, maybe not. FML.

screen shot 2018-10-02 at 9 41 28 am

**Comment by fionawhim** [comment]
ok this seems fixed

**Review by jessicamarcus — APPROVED** [review]
LGTM! Active state jank can be revisited whenever we end up reworking Fleet - I agree it's not a huge deal.

**Pull request merged**
