### PR TITLE
Adds combo-box support to the text field

### PR DESCRIPTION
**Pull request by finneganh**
(Ported from registry-certs and generalized)

screen shot 2017-12-07 at 11 55 23 am

### CODE REVIEW

**Comment by matthewcrist** [comment]
@finneganh looks broken in the PR deploy

screen shot 2017-12-07 at 12 35 32 pm

**Comment by finneganh** [comment]
@matthewcrist What browser? Can't repro.

**Comment by finneganh** [comment]
Percy seemed cool with it as well: https://percy.io/CityOfBoston/patterns/builds/434062

**Comment by finneganh** [comment]
goddamn fucking Safari.

**Comment by finneganh** [comment]
OK, updated to get Safari into gear.

**Comment by finneganh** [comment]
Thanks for the catch.

**Pull request merged**
