### PR TITLE
Search icon close button

### PR DESCRIPTION
**Pull request by mmcgowanBOS**
Updated "::before" pseduo class on search icon to include an "x" button once icon is checked/clicked.

### CODE REVIEW

**Review by jessicamarcus — CHANGES_REQUESTED** [review]
I’m guessing the `#searchIcon` id is a new addition; if so, can we update the documentation example in Fleet to reflect the change? I’m assuming this is the correct file: `/components/base/nav/nav.hbs`. Thanks!

**Review by davidrkupton — APPROVED** [review]
LGTM !

**Comment by mmcgowanBOS** [comment]
FYI: The #searchIcon is not a new addition. It's in the existing source code both on boston.gov and Death certs web app (https://registry.boston.gov/death)

**Comment by jessicamarcus** [comment]
Aha - thanks! I didn’t realize the Fleet example was so out-of-date. Would you mind updating in Fleet so we have accurate documentation?

(Death and the other webapps use a header that is automagically extracted as a static piece of HTML from boston.gov itself 🙃)

**Comment by mmcgowanBOS** [comment]
Yes. I updated Fleet directly on develop. See here.

https://github.com/CityOfBoston/patterns/blob/develop/components/base/nav/nav.hbs

**Comment by jessicamarcus** [comment]
👍 let’s try to keep all related changes together in the same feature branch/PR so we have a clear record if we need to refer back to this in the future.

**Review by jessicamarcus — APPROVED** [review]

**Comment by fionawhim** [comment]
@mmcgowanBOS Per the working agreement, all changes need to be made through PRs. Don't commit directly to `develop` or `production` branches.

**Pull request merged**
